flaviojmendes/trilhainfo

src/App.tsx, src/components/Logo/Logo.tsx
Criei um component para a logo, para começar o processo de simplificar a página.
=> Add logo component

src/frontend.ts
Links adicionado em vuejs:
- Documentação do Vue
- Curso completo e gratuito de Vue.js 3 do iniciante ao avançado do [Igor Halfeld](https://github.com/IgorHalfeld)
=> Adicionando curso e documentação do Vue

src/App.tsx
- Removido logo.svg que estava sendo importado mas não estava sendo utilizado. 
- Removido ChevronUpIcon que estava sendo importado mas não estava sendo utilizado. 
- Removido className="" que estava sem valor na div
- Adicionado o atributo **allowToggle** no Accordion onde ele permite abrir e fechar o Accordion, antes só era possível abrir, melhorando assim a navegação e a experiência do usuário.
**Antes:**
**Depois:**
=> Improvement: removed unused itens and added allowToggle in Accordion

src/App.tsx
Fixing text and add empty content message
=> Fixing text and add empty content message

src/frontend.ts
Added a playlist where you learn a lot about the React Native library
=> Added course on React Native

src/roadmaps/backend.ts, src/roadmaps/frontend.ts
- Coloquei um vídeo sobre Helmet e como ele funciona com o express.
- Adicionei também um conteúdo bem legal sobre orientação a eventos, nesse conteúdo além de ser explicado a arquitetura, é configurado junto um KAFKA + Java, é bem legal para quem quer começar aprender sobre EDA.
=> adição helmet e orientacao a eventos

src/roadmaps/frontend.ts
Adicionei alguns links sobre web components
=> Adding webcomponent materials

src/roadmaps/frontend.ts
Acrescentei uma breve descrição sobre os Module Bundlers e incluí o link da documentação oficial do Vite.
=> add vite official documentation

src/components/layouts/MainLayout.tsx, src/pages/RoadmapPage.tsx, src/roadmaps/community.ts
🌹Criei uma aba para "comunidades", onde adicionei diversos links de comunidades de discords, paginas do youtube e twitch, pra galera se conectar e consumir variados conteúdos / tirar dúvidas.
=> Feat  community page to discord/others contents

src/roadmaps/frontend.ts
Adicionei 2 conteúdos sobre o WebAssembly Blazor um link oficial da Microsoft e outro do canal Macoratti.
=> Adding Blazor content

src/components/Level/LevelItem.tsx, src/components/Roadmap/Roadmap.tsx, tailwind.config.js
Added a checkmark on content item if all it's checkboxes are checked.
=> Adding layout change if all checkboxes from a content item are checked.

package-lock.json, src/roadmaps/frontend.ts, yarn.lock
Adicionando a playlist "Aprenda os React Hooks!" em React (O Básico).
=> Add React Hooks playlist

src/roadmaps/community.ts
🌹Percebi que o texto que escrevi não estava tão inclusivo para outro público que não fosse o masculino, com isso, refiz algumas partes do texto;
🌹Correções ortográficas e de links quebrados;
=> Refactor  text and link corrections

src/roadmaps/backend.ts
Link para playlist de Rust do Bruno Rocha adicionado
=> Update backend.ts Rust section

src/roadmaps/frontend.ts
Removi o bloco duplicado de React Native e passei seu conteúdo para o remanescente
=> Removed duplicated React Native topic

src/roadmaps/backend.ts, src/roadmaps/community.ts, src/roadmaps/frontend.ts
Foram realizados os seguintes ajustes:
- Pequenos ajustes de escrita.
- Organização em ordem alfabética da seção Comunidade.
- Inclusão na seção Desafios para Praticar.
- Inclusão na seção Vídeo e Lives -> Twitch.
=> Organização e ajustes.

index.html
Ajuste no lang de "en" para "pt-br"
=> Ajuste no lang

src/roadmaps/frontend.ts
adicionando conteúdo nos módulos:
- HTML
- JavaScript
- Segurança
- Web Components
- React
- GraphQL
espero que tenha conseguido ajudar!
=> adicionando conteúdos

src/App.css, src/components/Level/LevelItem.tsx, src/roadmaps/backend.ts
- Adicionada uma animação ao marcar/desmarcar uma seção concluída;
- Captura de tela:
- Adicionados conteúdos de MongoDB ao módulo de NoSQL.
- Captura de tela:
=> Adicionando animação ao marcar/desmarcar uma seção concluída e mais.

README.md
Hi @flaviojmendes, I am adding two links about the collaboration on your readme.md file.
=> adding two links about the collaboration

src/roadmaps/devops.ts
Adição de conteúdo, nas seguintes categorias
- Python
- Conteitos de Sistemas Operacionais
- Usando Terminal
- Containers
- Gerenciamento de Configuração
- Provisionamento de Infraestrutura 
- Monitoramento de Infraestrutura
- Escolha um provedor de Nuvem
=> Contribuição com Conteudo sobre DevOps

src/roadmaps/frontend.ts
Curso gratuito do Willian Justen complementar ao Curso de Git e Github para Iniciantes.
Fix #64
=> Add Git/GitHub course to database

README.md
Adição do link da página do projeto para acesso.
=> :books: docs: Atualizaçao do README com referência

src/roadmaps/backend.ts
add mais um tópico de estudos, a Cloud Computing
e incluindo outros conteúdos como Nginx, Circuit Break e Graceful Degradation
=> 	modified:   src/roadmaps/backend.ts

src/roadmaps/frontend.ts
> 🎬 [Vídeo sobre Gerenciamento de estados com Pinia](https://www.youtube.com/watch?v=4DFrzPTif2E)
> 🌐[Link para a documentação](https://www.radix-ui.com/docs/primitives/overview/introduction)
> 🎬[Aulão de Stitches e Radix UI - dpw e Pedro Duarte (Radix UI Co-creator)](https://www.youtube.com/watch?v=c_hrvOaZRNo)
> 🌐[Jest](https://jestjs.io/pt-BR/docs/getting-started)
> 🌐[react-testing-library](https://testing-library.com/docs/react-testing-library/intro)
> 🌐[Cypress](https://docs.cypress.io/guides/getting-started/installing-cypress)
> 🌐[Enzyme](https://enzymejs.github.io/enzyme/)
> 🎬[Minicurso de Cypress - Agilizei](https://www.youtube.com/playlist?list=PLnUo-Rbc3jjyx5BVnG8MB7vNd5ecu2yP1)
=> Novos conteúdos 📚

src/roadmaps/backend.ts
Adição de conteúdo sobre MSSQL, propriedades ACID, técnicas de normalização é modelagem de dados, no lugar certo agora.
=> Conteúdo sobre ACID, Normalização e MSSQL - main

src/roadmaps/backend.ts
Adicionando mais material para estudo de go baseado em testes
=> :sparkles: Add more golang content

src/roadmaps/backend.ts
Adds YouTube video from [Filipe Deschamps](https://www.youtube.com/c/FilipeDeschamps) channel.
=> feat: add resource for the SOLID subject

src/roadmaps/backend.ts
Adicionando conteudo sobre redes, armazenamento, javascript e git / github
=> :sparkles: Add more content

src/roadmaps/frontend.ts
Adicionei uma categoria em React com uma ótima leitura para aprender estados nos componentes React
=> Adding study React State

src/roadmaps/devops.ts
I did not add the url to oficial documentation because it is English
=> add Traefik to reverse proxy section

src/roadmaps/devops.ts
Adicionado link para um vídeo introdutório de Docker do Diolinux e um link a uma página do Guia Foca sobre Sistemas de Arquivos
=> Add Filesystem and Docker links

src/roadmaps/frontend.ts
Referente a issue #100 :smile:
=> add SEO section to Frontend roadmap

src/pages/HomePage.tsx
Adiciona o alinhamento vertical para os cards que ficam por baixo, deixando um respiro entre eles.
=> fix: vertical alignment on homepage

src/components/Roadmap/Roadmap.tsx, src/entity/RoadmapItem.tsx, src/roadmaps/frontend.ts
EM PROGRESSO!
Modificações:
- Adicionei a categoria pratice e alguns links na aba HTML
=> Add section to new projects and ideas

src/roadmaps/react.ts
Foram adicionados conteúdos de:
- Portals
- Context
- Hooks avançados
- Refs
=> Some react content added

src/components/CheatSheets/CheatSheets.tsx, src/components/Level/LevelItem.tsx, src/components/Roadmap/Roadmap.tsx, src/components/layouts/MainLayout.tsx, src/pages/HomePage.tsx
Melhorando a acessibilidade do Trilha Info para usuários que usam leitores de tela para navegar na web.
1 - implementação de tags semânticas;
2 - Uso do aria-labelledby para melhorar a acessibilidade;
3 - Uso do aria-label para rotular a tag nav no cabecalho;
Obs: Tem algumas coisas que podem melhorar principalmente visando os usuarios que usam apenas o teclado para navegar na internet, mas em outro pr eu subo essas melhorias.
=> improve accessibility

README.md, translation/readme-en.md
related https://github.com/flaviojmendes/trilhainfo/issues/104
=> feat(translation): add readme translation to English

README.md
related https://github.com/flaviojmendes/trilhainfo/pull/118
=> fix(link): fix link to readme-en

src/roadmaps/backend.ts, src/roadmaps/devops.ts, src/roadmaps/items/ruby.ts
Adicionei o arquivo ruby.ts no diretorios de items e o inseri como variavel no json que contém os links dos cursos das trilhas.
=> Adiciona conteudo a trilha de ruby e cria o arquivo ruby.ts

src/roadmaps/items/rust.ts
=> Add Aprenda Rust série

src/roadmaps/backend.ts, src/roadmaps/items/go.ts
#Alteração realizada no backend mudando o formato da importação do component go e no formato do json do arquivo go.ts adicionando o atributo children
=> fix: #131 Conteudo de GoLang não abre

src/roadmaps/backend.ts, src/roadmaps/items/http.ts
Saber sobre HTTP para o backend quanto o frontend, já que toda a WEB se comunica dessa forma
=> add http on backend roadmap

src/App.css, src/App.tsx, src/components/CallToAction/CallToAction.tsx, src/components/Header/Header.tsx, src/components/HorizontalRoadmap/HorizontalLevelItem/HorizontalLevelItem.tsx, src/components/HorizontalRoadmap/HorizontalLevelItemContent/HorizontalLevelItemContent.tsx, src/components/HorizontalRoadmap/HorizontalRoadmapFooter/HorizontalRoadmapFooter.tsx, src/components/LevelItem/LevelItem.tsx, src/components/MainRoadmaps/MainRoadmaps.tsx, src/components/MobileMenu/MobileMenu.tsx, src/components/NewRoadmap/NewRoadmapEditor/NewRoadmapEditor.tsx, src/components/NewRoadmap/NewRoadmapPreview/NewRoadmapPreview.tsx, src/components/Note/Note.tsx, src/components/ProjectInfo/ProjectInfo.tsx, src/components/Roadmap/Roadmap.tsx, src/components/RoadmapButtons/ButtonElement.tsx, src/components/RoadmapButtons/index.tsx, src/components/Sponsors/Sponsors.tsx, src/components/UserArea/UserArea.tsx, src/components/layouts/MainLayout.tsx, src/index.css, src/main.tsx, src/pages/HomePage.tsx, src/pages/HorizontalRoadmapPage.tsx, src/pages/NewRoadmap.tsx, tailwind.config.js
Essa pull request resolve a issue #194 
- Passei as classes que estavam dentro do App.css e animações para a própria config do tailwind, assim possiblitiando você usar elas com outras propriedades, ex:
- Antes existia uma classe chamada `bd-red` que aplicava um vermelho mais escuro que o `red` existente na config do tailwind, agora eu adicionei o `dark-red` como uma cor a mais na tailwind-config, podendo usar a classe `border-dark-red` pra usar a cor da maneira correta com o tailwind.
- Arrumei os prolemas de espaçamento, estavam muito desalinhados. Mudei de todas as seções para sempre seguirem o mesmo padrão, inclusive o do `footer`, que pode não precisar no momento, mas caso precise no futuro, estará alinhado da maneira que todos estão.
- Adicionei feedback de hover nos botões.
Tive um …
=> Resolver responsividade e feedback nos botões

src/roadmaps/frontend.ts
Essa PR adiciona os conteúdos de typescript ao site, antes da parte de frameworks. Como pedido aqui #167
=> Feat/adding Typescript contents

src/roadmaps/frontend.ts
Bom momento, pessoal.
Estou de volta com mais um pr sobre acessibilidade na web, dessa vez estou adicionando dentro do roadmap de front-end conteúdos sobre acessibilidade na web.
Acessibilidade na web e um tema que venho estudando bastante (inclusive meu tcc esta sendo desenvolvido nessa area) e um dos grandes problemas para o contínuo problema da inacessibilidade na web é a falta de conhecimento dos desenvolvedores sobre as técnicas de implementação de acessibilidade.
Dessa forma, estou abrindo esse pr para adicionar conteúdos sobre essa temática que é tão importante.
Qualquer coisa estou a disposição tanto para ajudar no ensino da acessibilidade na web, como para corrigir ou melhorar os conteúdos .
Obrigado!!
=> add web-accessibility on front-end roadmap

.dockerignore, Dockerfile, README.md, docker-compose.yaml, translation/readme-en.md
Descrição:
Adiciona a possibilidade de rodar o projeto utilizando docker, assim evitando sujeira com as dependencias locais.
=> Adiciona Docker ao projeto

src/roadmaps/devops.ts
Descrição:
Adiciona aula de pulumi ao roadmap de devops
=> adiciona uma aula de pulumi ao roadmap de devops

.env.example, README.md, translation/readme-en.md
- Adicionei um arquivo de exemplo pro `.env.local` para a pessoa que quiser contribuir precisar apenas copiar o `.env.example` de exemplo para começar
- Alterei as docs tanto do inglês quanto português
=> docs: improve docs for contributions

src/components/HorizontalRoadmap/HorizontalLevelItemContent/index.tsx, src/components/Roadmap/index.tsx
=> feat: set default value to accordion

src/roadmaps/backend.ts
Adiciona vídeos sobre C# e bancos de dados.
=> Adicionados vídeos sobre C# e Banco de Dados

src/roadmaps/items/rust.ts
Bom momento, pessoal. Abrindo esse pr com a intenção de adicionar mais alguns conteúdos sobre a linguagem de programação Rust. Desde já agradeço.
=> feat: add-content-from-rust

src/roadmaps/devops.ts, src/roadmaps/items/cplusplus.ts
Foram adicionados conteúdos básicos sobre a linguagem C++.
Todos os vídeos e apostilas referentes a linguagem são usados nos cursos CI208, CI180 e CI183 de Programação de Computadores da Universidade Federal do Paraná.
Issue #239
=> feat(devops): Conteúdo sobre C++ adicionado

src/roadmaps/backend.ts, src/roadmaps/items/http.ts
=> adding http content

src/components/Header/index.tsx, src/components/Hero/index.tsx, src/components/MainRoadmaps/index.tsx, src/components/ProjectInfo/index.tsx
Oi pessoal, mais um pr com algumas melhorias de acessibilidade para a plataforma
1 - Adição do aria-label em dois links que fica na tag nav do header.  Sem o arial-label, o usuário que usa um leitor de tela, não saberá para qual local o link irá redirecionar, pois o link do "discord" e github não tem texto, apenas um ícone. Dessa forma com a adição do aria-label, quando o usuário com um leitor de tela passar pelo o link, o leitor de tela irá informar que ao clicar naquele link, o usuário será direcionado para o discord ou github ;
2 - Algumas melhorias nas tags de título da página, pois alguns usuários navegam em uma página web apenas pelas pelo nível dos títulos;
3 - Melhora na semântica do html.
Desde já agradeço a atenção, e qualquer coisa estou a disposição para tirar dúvidas ou …
=> accessibility_improvement

src/roadmaps/backend.ts
Eu adicionei alguns conteúdos meus na área de PHP. Preferi fazer tudo em um único PR para não poluir, mas caso queira remover alguma(s) sugestão(ões), fiquei à vontade.
Abraços e obrigado por esse projeto.
=> Adicionando links para PHP

src/roadmaps/items/http.ts
Adicionando um link relacionado a HTTP
=> Adicionando link em HTTP

src/roadmaps/backend.ts, src/roadmaps/frontend.ts
Adicionando links relacionados a segurança tanto na trilha de front-end quanto na de back-end. Na trilha de front eu adicionei somente os conteúdos que fazem sentido, por isso a lista de back está maior.
=> Segurança no front e back

src/roadmaps/backend.ts
Como eu já criei muitos PRs, decidi juntar a parte de princípios e mensageria em um único PR. 🙈
=> Boas práticas e mensageria

src/components/Glossary/index.tsx
Correção de função de request fetchData no index.tsx do componente Glossary para não-interrupção do ciclo da página.
=> Reformulado fetchData para media do Instagram
